// ─── Demo Data: realistic mock for UI preview without OAuth ───────────────────
export const DEMO_USER = {
  username: 'anishde12020',
  displayName: 'Anish De',
  bio: 'Building tools that help developers ship faster. Open source enthusiast.',
  avatarUrl: 'https://avatars.githubusercontent.com/u/63192431?v=4',
  profileUrl: 'https://github.com/anishde12020',
  institution: 'IIT Kharagpur',
  impactScore: 92,
  specialtyTag: 'Strong Frontend Developer',
  specialtyTagDetail: 'Specializes in UI/UX engineering, React, and modern web technologies',
  specialtyIcon: '🎨',
  currentStreak: 47,
  longestStreak: 112,
  totalCommits: 1847,
  mergedPRCount: 143,
  externalPRCount: 89,
  personalPRCount: 54,
  openPRCount: 8,
  prMergeRate: 95,
  reviewsGiven: 67,
  issuesOpened: 34,
  publicRepos: 48,
  followers: 312,
  following: 89,
  growthIndex: 23,
  scoreBreakdown: {
    externalPRScore: 312,
    personalPRScore: 162,
    commitScore: 184,
    reviewScore: 134,
    starMultiplierBonus: 89,
    rawTotal: 881,
  },
  languages: [
    { name: 'TypeScript', percentage: 38.2, color: '#2b7489' },
    { name: 'JavaScript', percentage: 27.4, color: '#f1e05a' },
    { name: 'Python',     percentage: 14.1, color: '#3572A5' },
    { name: 'Go',         percentage: 9.3,  color: '#00ADD8' },
    { name: 'Rust',       percentage: 6.8,  color: '#dea584' },
    { name: 'CSS',        percentage: 4.2,  color: '#563d7c' },
  ],
  monthlyGrowth: [
    { month: '2025-07', score: 42, commits: 78, prs: 4 },
    { month: '2025-08', score: 51, commits: 92, prs: 5 },
    { month: '2025-09', score: 48, commits: 86, prs: 5 },
    { month: '2025-10', score: 63, commits: 110, prs: 7 },
    { month: '2025-11', score: 58, commits: 99, prs: 6 },
    { month: '2025-12', score: 72, commits: 124, prs: 8 },
    { month: '2026-01', score: 67, commits: 118, prs: 7 },
    { month: '2026-02', score: 81, commits: 141, prs: 9 },
    { month: '2026-03', score: 76, commits: 133, prs: 8 },
    { month: '2026-04', score: 88, commits: 155, prs: 10 },
    { month: '2026-05', score: 91, commits: 162, prs: 11 },
    { month: '2026-06', score: 96, commits: 178, prs: 12 },
  ],
  recentMergedPRs: [
    { title: 'feat: add dark mode support', repoName: 'shadcn-ui', repoOwner: 'shadcn', repoStars: 68400, isExternal: true, mergedAt: '2026-06-15' },
    { title: 'fix: resolve hydration mismatch in SSR', repoName: 'next.js', repoOwner: 'vercel', repoStars: 124000, isExternal: true, mergedAt: '2026-06-08' },
    { title: 'perf: optimize bundle splitting', repoName: 'vite', repoOwner: 'vitejs', repoStars: 67000, isExternal: true, mergedAt: '2026-05-29' },
    { title: 'docs: improve contribution guidelines', repoName: 'react', repoOwner: 'facebook', repoStars: 228000, isExternal: true, mergedAt: '2026-05-20' },
    { title: 'feat: implement streaming API', repoName: 'gittrack', repoOwner: 'anishde12020', repoStars: 420, isExternal: false, mergedAt: '2026-05-12' },
  ],
  lastCacheUpdate: new Date().toISOString(),
};

export const DEMO_LEADERBOARD = [
  { rank: 1, username: 'anishde12020', displayName: 'Anish De', avatarUrl: 'https://avatars.githubusercontent.com/u/63192431?v=4', impactScore: 92, specialtyTag: 'Strong Frontend Developer', currentStreak: 47, mergedPRCount: 143, rankDelta: 0 },
  { rank: 2, username: 'prathikshetty', displayName: 'Prathik Shetty', avatarUrl: 'https://avatars.githubusercontent.com/u/54380?v=4', impactScore: 87, specialtyTag: 'Backend & Cloud Engineer', currentStreak: 31, mergedPRCount: 118, rankDelta: 1 },
  { rank: 3, username: 'shreyasv11', displayName: 'Shreyas V', avatarUrl: 'https://avatars.githubusercontent.com/u/58261?v=4', impactScore: 84, specialtyTag: 'AI & ML Engineer', currentStreak: 22, mergedPRCount: 97, rankDelta: -1 },
  { rank: 4, username: 'devanik21', displayName: 'Devanik', avatarUrl: 'https://avatars.githubusercontent.com/u/71243?v=4', impactScore: 79, specialtyTag: 'Systems Engineer', currentStreak: 18, mergedPRCount: 88, rankDelta: 2 },
  { rank: 5, username: 'krishnaprakash', displayName: 'Krishna Prakash', avatarUrl: 'https://avatars.githubusercontent.com/u/83921?v=4', impactScore: 74, specialtyTag: 'Mobile Engineer', currentStreak: 14, mergedPRCount: 76, rankDelta: -1 },
];
